export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';

export const SESSION_INFO_SUCCESS = 'SESSION_INFO_SUCCESS';
export const SESSION_INFO_FAIL = 'SESSION_INFO_FAIL';